#ifndef  FUNCS_CARDRES_FUNCS_H
#define  FUNCS_CARDRES_FUNCS_H

/*
**
** Function declarations for ACE Basic
**
** Note: Translated to ACE by Nils Sjoholm
**
** Date: 11-Oct-95 TO 14-Oct-95
**
*/              

#ifndef  EXEC_TYPES_H
#include <exec/types.h>
#endif

DECLARE FUNCTION STRUCTPTR OwnCard( STRUCTPTR _HANDLE ) LIBRARY cardres
DECLARE FUNCTION ReleaseCard( STRUCTPTR _HANDLE,  LONGINT flags ) LIBRARY cardres
DECLARE FUNCTION STRUCTPTR GetCardMap() LIBRARY cardres
DECLARE FUNCTION BOOL BeginCardAccess( STRUCTPTR _HANDLE ) LIBRARY cardres
DECLARE FUNCTION BOOL EndCardAccess( STRUCTPTR _HANDLE ) LIBRARY cardres
DECLARE FUNCTION LONGINT ReadCardStatus() LIBRARY cardres
DECLARE FUNCTION BOOL CardResetRemove( STRUCTPTR _HANDLE,  LONGINT flag ) LIBRARY cardres
DECLARE FUNCTION LONGINT CardMiscControl( STRUCTPTR _HANDLE, LONGINT control_bits ) LIBRARY cardres
DECLARE FUNCTION LONGINT CardAccessSpeed( STRUCTPTR _HANDLE,  LONGINT nanoseconds ) LIBRARY cardres
DECLARE FUNCTION LONGINT CardProgramVoltage( STRUCTPTR _HANDLE,  LONGINT voltage ) LIBRARY cardres
DECLARE FUNCTION BOOL CardResetCard( STRUCTPTR _HANDLE ) LIBRARY cardres
DECLARE FUNCTION BOOL CopyTuple( STRUCTPTR _HANDLE, ADDRESS buffer, LONGINT tuplecode,  LONGINT _SIZE ) LIBRARY cardres
DECLARE FUNCTION LONGINT DeviceTuple( ADDRESS tuple_data, STRUCTPTR storage ) LIBRARY cardres
DECLARE FUNCTION STRUCTPTR IfAmigaXIP( STRUCTPTR _HANDLE ) LIBRARY cardres
DECLARE FUNCTION BOOL CardForceChange() LIBRARY cardres
DECLARE FUNCTION LONGINT CardChangeCount() LIBRARY cardres
DECLARE FUNCTION LONGINT CardInterface() LIBRARY cardres
#endif   /* FUNCS_CARDRES_FUNCS_H */
